collections:
  careers:
    output: true
    permalink: /career/:name
  classes:
    output: true
    permalink: /class/:name
  categories:
    output: true
    permalink: /category/:name

defaults:
  - scope:
      path: ""
      type: "careers"
    values:
      layout: "career"
  - scope:
      path: ""
      type: "classes"
    values:
      layout: "class"
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"